### ISSUE TITLE
[Meta] First proofreading

### ISSUE THREAD

**Issue by bhajneet** [ShabadOS/database#846]
- [x] Sri Guru Granth Sahib Ji
- [ ] Dasam Granth
- [x] Vaaran Bhai Gurdaas ji (wip 80% complete)
- [ ] Nand Lal
- [ ] Amrit Kirtan (Sarabloh Granth)
- [ ] Kabit Saveiye

**Comment by bhajneet** [comment]
Merged with #847
