### ISSUE TITLE
[Meta] Database Checklist

### ISSUE THREAD

**Issue by bhajneet** [ShabadOS/database#847]
### Main
- [x] Import SGGS DB
- [x] Import Sri Dasam Granth
- [x] Import Bhai Gurdas Ji
- [x] Import Bhai Nand Lal Ji
- [x] Import Sarabloh Granth Baani

### Proofreading
- [x] SGGS
- [x] Sri Dasam Granth
- [x] Bhai Gurdas Ji Vaaran
- [x] Kabit Savaiye
- [x] Bhai Nand Lal Ji DB
- [x] Sarabloh Granth Baani

### Vishrams
- [x] Import Vishrams (SGGS Ji)
- [x] Corrections to Vishrams (SGGS Ji)
- [x] Import Vishrams (Sri Dasam Granth)
- [ ] Corrections to Vishrams (Sri Dasam Granth)
- [x] Import Vishrams (Bhai Gurdaas Ji)
- [ ] Import Vishraams (Bhai Nand Lal)

### Indexes
- [x] Import Sundar Gutka Index
- [x] Import Writer Index
- [x] Import Secton Index
- [x] Import SubSection Index
- [ ] Add SubSection ID's to Panktee's
- [ ] Import Amrit Keertan Index
- [ ] Link Shabads with Amrit Keertan Index

### Translations
- [x] Import Sant Singh Khalsa English Translation
- [x] Import Prof. Sahib Singh Teeka with Arths and Notes
- [x] Import Fareedkot Teeka
- [x] Import Bhai Manmohan Singh's Punjabi and English Translations
- [x] Import Spanish Translations
- ~~[ ] Import Giani Harbans Singh Teeka~~

### Others
- [x] Get Unicode Conversion Scripts Working
- [x] Get Hindi Transliteration Scripts Working
- [x] Get English Transliteration Scripts Working
- [ ] Import GurmatBibek Ucharan PDF's

This tracker is not for corrections/proofreading. See https://github.com/ShabadOS/database/issues/846

_Required for https://github.com/ShabadOS/database/issues/813_

**Comment by Sarabveer** [comment]
This was mainly for tracking progress for parity. No longer needed.
